<?php
session_start();
$price=array();
    $mname =  $_COOKIE["mname"];
    $tname =  $_COOKIE["tname"];
    $time = $_COOKIE["time"];
   $conn = new mysqli("localhost","root","admin","bms");
	// Check connection
	if ($conn->connect_error) {
		die("Connection failed: " . $conn->connect_error);
		}
	$sql = "SELECT mid FROM movie WHERE mname = '$mname'";
                    	$result = $conn->query($sql);
                        while($row = mysqli_fetch_assoc($result))
                        {$mid = $row['mid'];}	
    $sql1 = "SELECT tid FROM theatre WHERE tname = '$tname'";
                    	$result1 = $conn->query($sql1);
                        while($row1 = mysqli_fetch_assoc($result1))
                        {$tid = $row1['tid'];}
    $sql2 = "SELECT Sid FROM Shows WHERE tid = $tid AND mid = $mid AND timing = '$time'";
                    	$result2 = $conn->query($sql2);
                        $row = mysqli_fetch_assoc($result2);
                        $sid = $row['Sid'];
	$tickets =  $_COOKIE["tickets"];
	$data = json_decode($_COOKIE['checkbox'], true);
	echo "<br>";
	$uid = $_SESSION["userid"];
	for($i=0;$i<$tickets;$i++){
	$sql3 ="UPDATE seats SET userid = $uid WHERE sid = $sid AND seatid = $data[$i]";
	$conn->query($sql3);
	$sql4 = "SELECT cost FROM seats WHERE sid = $sid AND seatid = $data[$i]";
                    	$result4 = $conn->query($sql4);
                        while($row4 = mysqli_fetch_assoc($result4))
                        {$price[$i] = $row4['cost'];}
	}
	?>
<html>
    <title>Receipt: Lights Camera Action</title>
    <meta content="The final receipt generated by the website after confirmation of booking the tickets at a particular theater and a particular show. The receipt is given an ID."></meta>
<head>
    <style>
    img{
    height: 50px;
    width: 50px;
    }
    table, th, td {
    border: 1px white;
    }
    </style>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	<link rel='stylesheet' type='text/css' href='style.css' />
	<link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
	<script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
	<script type='text/javascript' src='js/example.js'></script>

</head>

<body>
<a href="homepage.php"><img src="home.png">
</a>
<fieldset>
<table id="meta" padding="1">
                <tr>
                    <td class="meta-head"><h4>Invoice#</h4></td>
                    <td><h4>000123</h4></td>
                </tr>
                <tr>

                    <td class="meta-head"><h4>Date<h4></td>
                    <?php echo "<td><h4>".date("Y-m-d")."</h4></td>"; ?>
                </tr>
				</table>
<br>
<br>
<br>
<hr>
<br>
	<div id="page-wrap">
		<center><h3 style="text-decoration: underline;">INVOICE</h3></center><br>
		<hr>
		<br>
		<div id="customer">
					<table id="meta" border="1">

                    <td class="meta-head"><h4>Movie</h4></td>
                    <td><h4><?php echo $mname; ?></h4></td>
                </tr>
				<tr>

                    <td class="meta-head"><h4>Theatre</h4></td>
                    <td><h4><?php echo $tname; ?></h4></td>
                </tr>
				<tr>

                    <td class="meta-head"><h4>Seats</h4></td>
                    <td><h4><?php echo $tickets; ?></h4></td>
                </tr>

            </table>
		</div>
		<br><hr>
		<table id="items">
		  <tr>
		      <th><h4>Seat No.</h4></th>
		      <th><h4>Price</h4></th>
		  </tr>
		  
		 
		  <?php
		  $sum=0;
		  for($i=0;$i<$tickets;$i++){
		  echo "<tr class='item-row'>";
		      echo "<center><td class='item-name'><div class='delete-wpr'><h4>$data[$i]</h4></div></td></center>";
		      echo "<td class='price'><h4>$price[$i]</h4></td>";
		  echo "</tr>";
		  $sum+=$price[$i];
		  }
		  ?>
		  </table>
		  <br>
		  <hr>
		  <br>
		  <table id="meta">
		  <tr>
		      
		      <td colspan="2"  class="meta-head"><h4>Total</h4></td>
		      <td class="total-value"><div id="subtotal"><h4><?php echo $sum; ?></h4></div></td>
		  </tr>
		  <tr>

		      
		      <td colspan="2" class="meta-head"><h4>GST</h4></td>
		      <td class="total-value"><div id="total"><h4><?php $y=0.18 *$sum; echo $y; ?></h4></div></td>
		  </tr>
		  
		  <tr>
		      
		      <td colspan="2" class="meta-head"><h4>Grand Total</h4></td>
		      <td class="total-value balance"><div class="due"><h4><?php echo $sum+$y; ?></h4></div></td>
		  </tr>
		</table>
	</div>
	<p hidden>receipt receipt receipt</p>
	<p hidden>url("http://img.nowrunning.com/content/movie/2017/newto-20338/bg4.jpg?fbrefresh=120122647321")</p>
</fieldset>	
</body>
</html>